code clean up
benjaglobant/Marvel-MVVM pull request #8
Opened 2020-06-04 16:28 UTC by MarcosCGlobant

In this PR i did a clean up of the code:
- Refactored ViewModelProvider with an extension function in an object.
- Warnings solved
- Indentation of modified classes
- Update libraries versions
- Organize dependencies on buildSystem folder

2020-06-04 18:00 UTC, MuroSar approved these changes

2020-06-04 20:03 UTC, lucianoeli approved these changes

2020-06-04 20:13 UTC, lucianoeli approved these changes
waiting for min api 23

2020-06-04 20:13 UTC, lucianoeli requested changes
waiting for min api 23

2020-06-04 20:14 UTC, lucianoeli approved these changes

2020-06-04 20:26 UTC, SartiMau approved these changes

2020-06-05 12:35 UTC, nicolbidone approved these changes

2020-06-05 12:36 UTC, merged